#define kontynuuj continue                                                         
#define liczba_calkowita int                                                       
#define pryncypalny main                                                                
#define pustka void                                                                
#define zwroc return                                                               
#define zero 0                                                                     
#define wskazanie_ze_wszystko_sie_powiodlo 0                                            
#define rowny =                                                                    
#define mniejszy_niz <
#define wiekszy_niz >
#define mniejszy_lub_rowny <<
#define wiekszy_lub_rowny >>
#define jeden_w_gore ++                                                            
#define dla for                                                                    
#define jezeliby if                                                                
#define wydrukuj printf                                                            
#define na_ekranie_liczbe "%d\n",

#define tak_wypadlo_ze (
#define to_wtedy )
