#define kontynuuj continue                                                         
#define liczba_calkowita int                                                       
#define pryncypalny main                                                                
#define pustka void                                                                
#define zwroc return                                                               
#define zero 0                                                                     
#define wskazanie_ze_masz_problem 1
#define zero 0
#define prawda 1
#define nieprawda 0
#define liczba_zmiennoprzecinkowa_pojedynczej_precyzji float
#define liczba_zmiennoprzecinkowa_podwojnej_precyzji double
#define wskazanie_ze_wszystko_sie_powiodlo 0                                            
#define rowny =                                                                    
#define faktycznie_taki_sam_jak ==
#define mniejszy_niz <
#define wiekszy_niz >
#define mniejszy_lub_rowny <<
#define wiekszy_lub_rowny >>
#define jeden_w_gore ++                                                            
#define dla for                                                                    
#define jezeliby if                                                                
#define gdyby_tak_sie_zdarzylo_przypadkiem_ze if
#define nie_masz_racji 0
#define w_innym_wypadku else
#define wydrukuj printf                                                            
#define na_ekranie_liczbe "%d\n",

#define dodac +
#define odjac -
#define przemnozone_przez *
#define podzielone_przez /

#define tak_wypadlo_ze (
#define to_wtedy )
